// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.zoo.grpc.api;

public interface RPCDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zoo.grpc.api.RPCDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
