// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.zoo.grpc.api;

public final class RPCDateServiceApi {
  private RPCDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zoo_grpc_api_RPCDateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zoo_grpc_api_RPCDateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zoo_grpc_api_RPCDateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zoo_grpc_api_RPCDateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ndemo.proto\022\020com.zoo.grpc.api\"\"\n\016RPCDat" +
      "eRequest\022\020\n\010userName\030\001 \001(\t\"%\n\017RPCDateRes" +
      "ponse\022\022\n\nserverDate\030\001 \001(\t2b\n\016RPCDateServ" +
      "ice\022P\n\007getDate\022 .com.zoo.grpc.api.RPCDat" +
      "eRequest\032!.com.zoo.grpc.api.RPCDateRespo" +
      "nse\"\000B\'\n\020com.zoo.grpc.apiB\021RPCDateServic" +
      "eApiP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zoo_grpc_api_RPCDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zoo_grpc_api_RPCDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zoo_grpc_api_RPCDateRequest_descriptor,
        new String[] { "UserName", });
    internal_static_com_zoo_grpc_api_RPCDateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zoo_grpc_api_RPCDateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zoo_grpc_api_RPCDateResponse_descriptor,
        new String[] { "ServerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
